[profile.default]
solc_version = '0.8.13'
optimizer_runs = 1_000_000
verbosity = 1
fuzz_runs = 5
remappings = [
    'forge-std/=lib/forge-std/src/',
    'ds-test/=lib/forge-std/lib/ds-test/src/',
    'openzeppelin-contracts/=lib/openzeppelin-contracts/contracts/'
]
