[profile.default]
solc_version = '0.8.15'
optimizer_runs = 1_000_000
verbosity = 1
fuzz_runs = 5
remappings = [
    'forge-std/=lib/forge-std/src/',
    'openzeppelin-contracts/=lib/openzeppelin-contracts/contracts/'
]
[fmt]
line_length = 100
